// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JSONser.proto
// Protobuf C++ Version: 5.26.0

#include "JSONser.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ConfigResponses::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : files_{},
        requests_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        maxresponses_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConfigResponses::ConfigResponses(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConfigResponsesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigResponsesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigResponsesDefaultTypeInternal() {}
  union {
    ConfigResponses _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigResponsesDefaultTypeInternal _ConfigResponses_default_instance_;

inline constexpr Answer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : docid_{},
        _docid_cached_byte_size_{0},
        rank_{},
        idrequest_{0},
        result_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Answer::Answer(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AnswerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnswerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnswerDefaultTypeInternal() {}
  union {
    Answer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnswerDefaultTypeInternal _Answer_default_instance_;
static ::_pb::Metadata file_level_metadata_JSONser_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_JSONser_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_JSONser_2eproto = nullptr;
const ::uint32_t
    TableStruct_JSONser_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ConfigResponses, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ConfigResponses, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::ConfigResponses, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::ConfigResponses, _impl_.maxresponses_),
        PROTOBUF_FIELD_OFFSET(::ConfigResponses, _impl_.files_),
        PROTOBUF_FIELD_OFFSET(::ConfigResponses, _impl_.requests_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Answer, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Answer, _impl_.idrequest_),
        PROTOBUF_FIELD_OFFSET(::Answer, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::Answer, _impl_.docid_),
        PROTOBUF_FIELD_OFFSET(::Answer, _impl_.rank_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ConfigResponses)},
        {13, -1, -1, sizeof(::Answer)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ConfigResponses_default_instance_._instance,
    &::_Answer_default_instance_._instance,
};
const char descriptor_table_protodef_JSONser_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rJSONser.proto\"g\n\017ConfigResponses\022\014\n\004na"
    "me\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\024\n\014maxResponse"
    "s\030\003 \001(\005\022\r\n\005files\030\004 \003(\t\022\020\n\010requests\030\005 \003(\t"
    "\"H\n\006Answer\022\021\n\tidRequest\030\001 \001(\005\022\016\n\006result\030"
    "\002 \001(\010\022\r\n\005docid\030\003 \003(\005\022\014\n\004rank\030\004 \003(\002b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_JSONser_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_JSONser_2eproto = {
    false,
    false,
    202,
    descriptor_table_protodef_JSONser_2eproto,
    "JSONser.proto",
    &descriptor_table_JSONser_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_JSONser_2eproto::offsets,
    file_level_metadata_JSONser_2eproto,
    file_level_enum_descriptors_JSONser_2eproto,
    file_level_service_descriptors_JSONser_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_JSONser_2eproto_getter() {
  return &descriptor_table_JSONser_2eproto;
}
// ===================================================================

class ConfigResponses::_Internal {
 public:
};

ConfigResponses::ConfigResponses(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ConfigResponses)
}
inline PROTOBUF_NDEBUG_INLINE ConfigResponses::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : files_{visibility, arena, from.files_},
        requests_{visibility, arena, from.requests_},
        name_(arena, from.name_),
        version_(arena, from.version_),
        _cached_size_{0} {}

ConfigResponses::ConfigResponses(
    ::google::protobuf::Arena* arena,
    const ConfigResponses& from)
    : ::google::protobuf::Message(arena) {
  ConfigResponses* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.maxresponses_ = from._impl_.maxresponses_;

  // @@protoc_insertion_point(copy_constructor:ConfigResponses)
}
inline PROTOBUF_NDEBUG_INLINE ConfigResponses::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : files_{visibility, arena},
        requests_{visibility, arena},
        name_(arena),
        version_(arena),
        _cached_size_{0} {}

inline void ConfigResponses::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.maxresponses_ = {};
}
ConfigResponses::~ConfigResponses() {
  // @@protoc_insertion_point(destructor:ConfigResponses)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConfigResponses::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.version_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ConfigResponses::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_._cached_size_),
              false,
          },
          &ConfigResponses::MergeImpl,
          &ConfigResponses::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ConfigResponses::Clear() {
// @@protoc_insertion_point(message_clear_start:ConfigResponses)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.files_.Clear();
  _impl_.requests_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.version_.ClearToEmpty();
  _impl_.maxresponses_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConfigResponses::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 48, 2> ConfigResponses::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ConfigResponses_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ConfigResponses>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.name_)}},
    // string version = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.version_)}},
    // int32 maxResponses = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConfigResponses, _impl_.maxresponses_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.maxresponses_)}},
    // repeated string files = 4;
    {::_pbi::TcParser::FastUR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.files_)}},
    // repeated string requests = 5;
    {::_pbi::TcParser::FastUR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.requests_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string version = 2;
    {PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 maxResponses = 3;
    {PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.maxresponses_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated string files = 4;
    {PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.files_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string requests = 5;
    {PROTOBUF_FIELD_OFFSET(ConfigResponses, _impl_.requests_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\17\4\7\0\5\10\0\0"
    "ConfigResponses"
    "name"
    "version"
    "files"
    "requests"
  }},
};

::uint8_t* ConfigResponses::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ConfigResponses)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ConfigResponses.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string version = 2;
  if (!this->_internal_version().empty()) {
    const std::string& _s = this->_internal_version();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ConfigResponses.version");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int32 maxResponses = 3;
  if (this->_internal_maxresponses() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_maxresponses(), target);
  }

  // repeated string files = 4;
  for (int i = 0, n = this->_internal_files_size(); i < n; ++i) {
    const auto& s = this->_internal_files().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ConfigResponses.files");
    target = stream->WriteString(4, s, target);
  }

  // repeated string requests = 5;
  for (int i = 0, n = this->_internal_requests_size(); i < n; ++i) {
    const auto& s = this->_internal_requests().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ConfigResponses.requests");
    target = stream->WriteString(5, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ConfigResponses)
  return target;
}

::size_t ConfigResponses::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ConfigResponses)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string files = 4;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_files().size());
  for (int i = 0, n = _internal_files().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_files().Get(i));
  }
  // repeated string requests = 5;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_requests().size());
  for (int i = 0, n = _internal_requests().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_requests().Get(i));
  }
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string version = 2;
  if (!this->_internal_version().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_version());
  }

  // int32 maxResponses = 3;
  if (this->_internal_maxresponses() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_maxresponses());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ConfigResponses::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ConfigResponses*>(&to_msg);
  auto& from = static_cast<const ConfigResponses&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConfigResponses)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_files()->MergeFrom(from._internal_files());
  _this->_internal_mutable_requests()->MergeFrom(from._internal_requests());
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_version().empty()) {
    _this->_internal_set_version(from._internal_version());
  }
  if (from._internal_maxresponses() != 0) {
    _this->_impl_.maxresponses_ = from._impl_.maxresponses_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConfigResponses::CopyFrom(const ConfigResponses& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConfigResponses)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConfigResponses::IsInitialized() const {
  return true;
}

void ConfigResponses::InternalSwap(ConfigResponses* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.files_.InternalSwap(&other->_impl_.files_);
  _impl_.requests_.InternalSwap(&other->_impl_.requests_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_, &other->_impl_.version_, arena);
        swap(_impl_.maxresponses_, other->_impl_.maxresponses_);
}

::google::protobuf::Metadata ConfigResponses::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_JSONser_2eproto_getter,
                                   &descriptor_table_JSONser_2eproto_once,
                                   file_level_metadata_JSONser_2eproto[0]);
}
// ===================================================================

class Answer::_Internal {
 public:
};

Answer::Answer(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Answer)
}
inline PROTOBUF_NDEBUG_INLINE Answer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : docid_{visibility, arena, from.docid_},
        _docid_cached_byte_size_{0},
        rank_{visibility, arena, from.rank_},
        _cached_size_{0} {}

Answer::Answer(
    ::google::protobuf::Arena* arena,
    const Answer& from)
    : ::google::protobuf::Message(arena) {
  Answer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, idrequest_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, idrequest_),
           offsetof(Impl_, result_) -
               offsetof(Impl_, idrequest_) +
               sizeof(Impl_::result_));

  // @@protoc_insertion_point(copy_constructor:Answer)
}
inline PROTOBUF_NDEBUG_INLINE Answer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : docid_{visibility, arena},
        _docid_cached_byte_size_{0},
        rank_{visibility, arena},
        _cached_size_{0} {}

inline void Answer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, idrequest_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, idrequest_) +
               sizeof(Impl_::result_));
}
Answer::~Answer() {
  // @@protoc_insertion_point(destructor:Answer)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Answer::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Answer::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Answer, _impl_._cached_size_),
              false,
          },
          &Answer::MergeImpl,
          &Answer::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Answer::Clear() {
// @@protoc_insertion_point(message_clear_start:Answer)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.docid_.Clear();
  _impl_.rank_.Clear();
  ::memset(&_impl_.idrequest_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.result_) -
      reinterpret_cast<char*>(&_impl_.idrequest_)) + sizeof(_impl_.result_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Answer::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> Answer::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Answer_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Answer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float rank = 4;
    {::_pbi::TcParser::FastF32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Answer, _impl_.rank_)}},
    // int32 idRequest = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Answer, _impl_.idrequest_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Answer, _impl_.idrequest_)}},
    // bool result = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Answer, _impl_.result_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Answer, _impl_.result_)}},
    // repeated int32 docid = 3;
    {::_pbi::TcParser::FastV32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Answer, _impl_.docid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 idRequest = 1;
    {PROTOBUF_FIELD_OFFSET(Answer, _impl_.idrequest_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool result = 2;
    {PROTOBUF_FIELD_OFFSET(Answer, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated int32 docid = 3;
    {PROTOBUF_FIELD_OFFSET(Answer, _impl_.docid_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated float rank = 4;
    {PROTOBUF_FIELD_OFFSET(Answer, _impl_.rank_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Answer::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Answer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 idRequest = 1;
  if (this->_internal_idrequest() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_idrequest(), target);
  }

  // bool result = 2;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_result(), target);
  }

  // repeated int32 docid = 3;
  {
    int byte_size = _impl_._docid_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          3, _internal_docid(), byte_size, target);
    }
  }

  // repeated float rank = 4;
  if (this->_internal_rank_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_rank(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Answer)
  return target;
}

::size_t Answer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Answer)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 docid = 3;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_docid())
    ;
    _impl_._docid_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float rank = 4;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_rank_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // int32 idRequest = 1;
  if (this->_internal_idrequest() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_idrequest());
  }

  // bool result = 2;
  if (this->_internal_result() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Answer::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Answer*>(&to_msg);
  auto& from = static_cast<const Answer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Answer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_docid()->MergeFrom(from._internal_docid());
  _this->_internal_mutable_rank()->MergeFrom(from._internal_rank());
  if (from._internal_idrequest() != 0) {
    _this->_impl_.idrequest_ = from._impl_.idrequest_;
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Answer::CopyFrom(const Answer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Answer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Answer::IsInitialized() const {
  return true;
}

void Answer::InternalSwap(Answer* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.docid_.InternalSwap(&other->_impl_.docid_);
  _impl_.rank_.InternalSwap(&other->_impl_.rank_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Answer, _impl_.result_)
      + sizeof(Answer::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(Answer, _impl_.idrequest_)>(
          reinterpret_cast<char*>(&_impl_.idrequest_),
          reinterpret_cast<char*>(&other->_impl_.idrequest_));
}

::google::protobuf::Metadata Answer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_JSONser_2eproto_getter,
                                   &descriptor_table_JSONser_2eproto_once,
                                   file_level_metadata_JSONser_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_JSONser_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
